sudo: required
services:
  - docker

before_install:
  - docker build -t borche/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true borche/react-test npm test

after_success:
  - docker build -t borche/complex-client ./client
  - docker build -t borche/complex-nginx ./nginx
  - docker build -t borche/complex-api ./server
  - docker build -t borche/complex-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push borche/complex-client
  - docker push borche/complex-nginx
  - docker push borche/complex-api
  - docker push borche/complex-worker
